import { NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'
import { createClient } from '@/lib/supabase-server'
import { SUMMARY_STYLES, FIELD_LABELS, type SummaryStyle } from '@/lib/prompts'

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

interface ChatMessage {
  role: 'user' | 'assistant'
  content: string
}

function summaryToContext(content: string, style: string, title: string): string {
  let parsed: Record<string, unknown>
  try { parsed = JSON.parse(content) } catch { return content }

  const styleInfo = SUMMARY_STYLES[style as SummaryStyle]
  const lines: string[] = [`# ${title} — ${styleInfo.label} Summary\n`]

  for (const [key, value] of Object.entries(parsed)) {
    if (key === 'title') continue
    const label = FIELD_LABELS[key] ?? key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
    lines.push(`\n## ${label}`)

    if (Array.isArray(value)) {
      for (const item of value as unknown[]) {
        if (typeof item === 'string') {
          lines.push(`- ${item.replace(/\*\*/g, '').replace(/\*/g, '')}`)
        } else if (typeof item === 'object' && item !== null) {
          const obj = item as Record<string, unknown>
          const page = typeof obj.page === 'number' ? ` (p. ${obj.page})` : ''
          const { page: _p, ...rest } = obj
          const parts = Object.values(rest).map(v => String(v).replace(/\*\*/g, '').replace(/\*/g, ''))
          lines.push(`- ${parts.join(' — ')}${page}`)
        }
      }
    } else {
      lines.push(String(value).replace(/\*\*/g, '').replace(/\*/g, ''))
    }
  }

  return lines.join('\n')
}

export async function POST(request: Request) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { summaryId, messages } = await request.json() as {
    summaryId: string
    messages: ChatMessage[]
  }

  if (!summaryId || !messages?.length) {
    return NextResponse.json({ error: 'Missing summaryId or messages' }, { status: 400 })
  }

  const { data: summary } = await supabase
    .from('summaries')
    .select('content, style, file_name')
    .eq('id', summaryId)
    .eq('user_id', user.id)
    .single()

  if (!summary) return NextResponse.json({ error: 'Summary not found' }, { status: 404 })

  const title = (() => {
    try {
      const p = JSON.parse(summary.content) as Record<string, unknown>
      return typeof p.title === 'string' ? p.title : summary.file_name
    } catch { return summary.file_name }
  })()

  const context = summaryToContext(summary.content, summary.style, title)

  const response = await anthropic.messages.create({
    model: 'claude-haiku-4-5',
    max_tokens: 600,
    system: `You are a reading assistant helping the user explore a book summary generated by BookDigest.

Here is the summary:

${context}

Answer questions concisely based on this summary. If asked about something not covered, say so and mention what is covered. Don't repeat large chunks of the summary verbatim — synthesize and explain. Keep answers under 200 words unless the user asks for detail.`,
    messages: messages.map(m => ({ role: m.role, content: m.content })),
  })

  const answer = response.content[0].type === 'text' ? response.content[0].text : ''
  return NextResponse.json({ answer })
}
